### ISSUE TITLE
В Наши документы ссылки на документы сливаются с фоном

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#11]
http://mini7.nava.baikalweb.com/documents
Предлагаю разрезать на блоки, по типу 7 шагов.
В каждом блоке представить:
1) Название документа
2) Краткое описание
3) Кнопка скачать

**Comment by alexfourth** [comment]
Цвет ссылок на документы в соответствии с mini7/issues/13.

**Comment by alexfourth** [comment]
Как и говорили, везде (где возможно) используем лесенку.
Сделал на базе Д7 шаблон для документов http://mini7.nava.baikalweb.com/page2/34.

**Comment by als-studio** [comment]
Пример страницы документов.
Цвета иконок можно сделать другими, так же можно разными цветами обозначать разные типы файлов.
Шрифт на кнопке будет таким же, как на остальных страницах - Roboto.

![doc](https://cloud.githubusercontent.com/assets/1411640/7135716/17456502-e2dc-11e4-9e8a-d12b0663cca3.png)

**Comment by alexfourth** [comment]
как я понимаю первое и второе можно будет менять.
````
Цвета иконок можно сделать другими, 
````
````
так же можно разными цветами обозначать разные типы файлов.
````

Pеализуем в таком виде.

**Comment by als-studio** [comment]
Сделали: http://mini7.nava.baikalweb.com/files

**Comment by alexfourth** [comment]
несколько комментариев.
1) Страница д.б. в Как мы работаем -> Наши документы (в не root menu)
2) Очень большие интервалы между документами  (на макете и др. стараницах
сайте меньше)
3) Кнопка СКАЧАТЬ на макете выглядела интереснее

2015-04-24 12:15 GMT+02:00 Anton L. Safin <notifications@github.com>:

> Сделали: http://mini7.nava.baikalweb.com/files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bayclosed/mini7/issues/11#issuecomment-95882193>.
>



-- 
Удачи.
Alexander

**Comment by als-studio** [comment]
2 - done
3 - done

**Comment by alexfourth** [comment]
ok, есть возможность поправить первый пункт чтобы закрыть issue?
````
2 - done
3 - done
````

**Comment by als-studio** [comment]
>есть возможность поправить первый пункт чтобы закрыть issue?
Да, в процессе.

**Comment by als-studio** [comment]
Сделано: http://mini7.nava.baikalweb.com/documents
Выглядит "вкладка", как и предупреждали, несколько странно :(

**Comment by alexfourth** [comment]
Есть немного, но совсем немного (на планшете даже гармонично).
Правда, кнопка немного смещена влево, но окончательно будет видно что и как после наполнения контентом.
