### ISSUE TITLE
Какого цвета должны быть ссылки в тексте?

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#13]
Не нашли в макетах ни одного примера ссылки в тексте (на белом фоне). Сейчас ссылки желтые, но на белом (сером) фоне они абсолютно не читаются: https://yadi.sk/i/fap7Y6abfWHkq
Есть ли какие-то предпочтения или пожелания по тому, каким цветом оформлять такие ссылки?

**Comment by alexfourth** [comment]
Двигаемся в сторону красного, иначе все сливается.
Как я понимаю, стиль можно подправить потом.
````
Есть ли какие-то предпочтения или пожелания по тому, каким цветом оформлять такие ссылки?
````

**Comment by als-studio** [comment]
См. такой вариант цвета ссылок: http://mini7.nava.baikalweb.com/documents

**Comment by alexfourth** [comment]
Цвет нормально, сама орг-ция раздела см. issues/11.
