### ISSUE TITLE
тестирование производительности на площадке Заказчика

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#14]
Развернули из  доступного в github кода + pgdump.

http://poop.mini7.ru:6251/

Судя по контенту выдачи сайта, предоставленные копии не соответствуют полностью текущему оригиналу. Посмотрите пож.

**Comment by mrsad** [comment]
а доступа туда никак нельзя получить? ssh или ftp, хотя-бы. папку с файлами, которой в гите нет, надо залить.

**Comment by mrsad** [comment]
http://poop.mini7.ru:6251/?q=admin/config/media/file-system

вот тут ошибки.
Warning: file_put_contents(temporary://filegZC5k4): failed to open stream: "DrupalTemporaryStreamWrapper::stream_open" call failed в функции file_unmanaged_save_data() (строка 1936 в файле /var/www/html/includes/file.inc).
Невозможно создать файл.
Warning: file_put_contents(temporary://filelloeTz): failed to open stream: "DrupalTemporaryStreamWrapper::stream_open" call failed в функции file_unmanaged_save_data() (строка 1936 в файле /var/www/html/includes/file.inc).
Невозможно создать файл.
Warning: mkdir(): Permission denied в функции drupal_mkdir() (строка 2413 в файле /var/www/html/includes/file.inc).
Каталог sites/default/private не существует и не может быть создан.
Warning: mkdir(): Permission denied в функции drupal_mkdir() (строка 2413 в файле /var/www/html/includes/file.inc).
Каталог sites/default/tmp не существует и не может быть создан.

**Comment by bayclosed** [comment]
первоначально для записи был открыт только sites/default/files

Теперь разрешил запись в sites/default/private (замапплен туда же, куда и sites/default/files) и sites/default/tmp (на всякий случай).

0. сайт по-прежнему выглядит .. минималистично
1. остальные файлы и директории RO. Нужны ли ещё куда права?
2. правильно ли я понял, что sites/default/private заменяет sites/default/files - или это разные директории (для чего?)
3. нужна ли tmp и там ли (sites/default/tmp)?

**Comment by mrsad** [comment]
не грузятся стили, скрипты, картинки. например http://poop.mini7.ru:6251/misc/jquery.once.js?v=1.2
не работают "чистые" URL-ы. Вот конфиг, который мы используем https://gist.github.com/mrsad/63bb93aa293dbe537fa7

**Comment by mrsad** [comment]
Архив нашей папки sites/default - http://dev.baikalweb.com/mini7-default.tar.gz

**Comment by bayclosed** [comment]
Прошу привести полный список директорий/файлов, куда php-fpm должен иметь право писать

**Comment by mrsad** [comment]
sites/default/files
sites/default/private
sites/default/tmp


01.04.2015 0:26, Gleb Kuzmenko пишет:
> Прошу привести полный список директорий/файлов, куда php-fpm должен
> иметь право писать

**Comment by als-studio** [comment]
Проверьте, пожалуйста, разрешены ли на сервере исходящие соединения и подключена ли библиотека php soap

**Comment by bayclosed** [comment]
Исходящие разрешены, php soap полключена

**Comment by als-studio** [comment]
Можно закрывать?

**Comment by alexfourth** [comment]
работа пробложена в #12.
