### ISSUE TITLE
Экспорт данных с D6 на D7

### ISSUE THREAD

**Issue by chernetsky** [bayclosed/mini7#15]
С кем можно пообщаться по поводу старой структуры данных? Необходимо понять как на старом сайте связаны пользователи и материалы типа Покупатель и Турист. 

Также нужен свежий дамп базы. Есть ощущение, что тот дамп, с которым я имею дело, не содержит реальных данных.

Мой скайп s.chernetsky

**Comment by alexfourth** [comment]
````
С кем можно пообщаться по поводу старой структуры данных? 
Необходимо понять как на старом сайте связаны 
пользователи и материалы типа Покупатель и Турист.
````
Ниже разъяснения и несколько примеров, если будут вопросы, - дайте знать (сюда же),
я на Вас выйду по skype.

Информация о Покупателе/Туристе/Заказе/Туре представлена в текущей версии (Д6)
далеко не идеальным образом. Копировать структуры один в один не нужно (не рекомендуется).


Пользователь = Покупатель 
Покупатель делает заказ и оплачивает Тур.
Покупатель может быть туристом, а может и нет.

Проверка является ли покупатель туристом (rows >0 - > ДА) по определенному Заказу:
	$sql='select * from node where nid in (select nid from tourindextourists where tourorderid='.$order_item['id'].') and
					type=\'customer\'';


Информация о покупателе/пользователе:
	$sql=' select c.*,n.title from content_type_customer c, node n where
					c.nid=n.nid and n.uid='.$uid.' and n.type=\'customer\'';


Информация о туристах по определенному Заказу:				
	$sql="select * from content_type_tourist where nid in (Select nid from tourindextourists where tourorderid=".$order_item['id'].")";

Информация о Заказе:
	$sql='select * from tourindexorders where id='.$order_item['id'];				

Детальная информация о туре:
	$sql='select * from tourindex_xml where tbltourid='.$order_item['id'];


````
Также нужен свежий дамп базы. Есть ощущение, что тот дамп, с которым я имею дело, не содержит реальных данных.
````
Дамп у Вас достаточно свежий, там есть все данные, но они немного перемешаны.

**Comment by chernetsky** [comment]
Спасибо, стало яснее!

Ещё такие вопросы по старой структуре: 
1. Родные юзеры друпала какую-то роль в этой системе играют? Судя по дампу там только спамеры. Тогда как клиенты логинились на сайте?
2. В админке старого сайта как-то можно посмотреть конкретного Покупателя? Вы с ними работаете в админке - создаёте/просматриваете/редактируете? Или все операции с ними делаются программно? Я пытаюсь зайти в какой-нибудь материал типа Покупатель, и вижу данные "Администратора Администраторовича".

Новую структуру хотим организовать так:
Используем друпал-юзеров как покупателей. У юзера есть:
1. Коллекция полей "Покупатель", соответствующая полям Покупателя из старой структуры.
2. Коллекция полей "Турист", соответствующая старому Туристу. Туристов у юзера может быть неограниченное количество.

План экспорта такой: 
1. Используя список Покупателей из старой структуры создать в новой структуре новых друпал-юзеров с заполненными Покупателями.
2. Используя Туристов из старой структуры, заполнить поля Турист в юзерах.

Если по этому плану или по тому, как видим новую структуру, есть какие-то вопросы - пишите!

**Comment by chernetsky** [comment]
По поводу того дампа, который у нас есть, всё-таки не понятно. 

У нас и в таблице users и в таблице content_type_customer странные данные. Вот, например, кусок содержимого content_type_customer:
http://mini7.che.baikalweb.com/import-d6-customers.php?op=customers

Выполняется запрос 'SELECT c.* FROM content_type_customer c LIMIT 1000'

Используем дамп 
https://www.dropbox.com/s/7cdgkmkxkz2x0gh/mini7-pg94.Fc?dl=0 

Ещё скажите какую версию PostgreSQL используем? Может какие-то специфичные настройки, ключи или ещё что-то? У нас специалиста по PostgreSQL нет, может мы как-то неправильно залили При импорте дампа были какие-то ошибки - не знаем, критично или нет.

**Comment by alexfourth** [comment]
3 апреля 2015 г., 4:33 пользователь Sergey Chernetsky <
notifications@github.com> написал:

> Спасибо, стало яснее!
>
> Ещё такие вопросы по старой структуре:
> 1. Родные юзеры друпала какую-то роль в этой системе играют? Судя по дампу
> там только спамеры.
>
Как я понимаю, Вы пишете модуль для миграции данных из D6(старая структура)
в D7(новая структура).
Т.е. будет модуль, который будет содержать mapping&rules.

> Тогда как клиенты логинились на сайте?
>
Используя логин и пароль. Все логины/email уникальны в системе.

Все модули (не родные) - sites/all/modules/custom.

Правила заполнения:
sites/all/modules/custom/ctourindex/validations.inc

> 2. В админке старого сайта как-то можно посмотреть конкретного Покупателя?
> Вы с ними работаете в админке - создаёте/просматриваете/редактируете? Или
> все операции с ними делаются программно? Я пытаюсь зайти в какой-нибудь
> материал типа Покупатель, и вижу данные "Администратора Администраторовича".
>
Можно ссылку, чтобы понимать что Вы видете.

Для работы с заявками используется другая система. Скрипт раз в 5 минут
забирает свежие заявки из Друпала,
их дальнейшая обоработка происходит в другой системе.
Необходимо в Д7 реализовать возможность видеть/редактировать эти данные
(тем более друпал дает такую возможность),
так как планируется увести всю обработку заявок в Друпал (не в рамках
текущего проекта).

Для тестов в текущей системе:
mini7.ru - test_my/als



> Новую структуру хотим организовать так:
> Используем друпал-юзеров как покупателей. У юзера есть:
> 1. Коллекция полей "Покупатель", соответствующая полям Покупателя из
> старой структуры.
>
ок

> 2. Коллекция полей "Турист", соответствующая старому Туристу. Туристов у
> юзера может быть неограниченное количество.
>
ок

> План экспорта такой:
> 1. Используя список Покупателей из старой структуры создать в новой
> структуре новых друпал-юзеров с заполненными Покупателями.
>
ок

> 2. Используя Туристов из старой структуры, заполнить поля Турист в юзерах.
>
ок

**Comment by alexfourth** [comment]
3 апреля 2015 г., 8:46 пользователь Sergey Chernetsky <notifications@github
.com> написал:

> По поводу того дампа, который у нас есть, всё-таки не понятно.
>
> У нас и в таблице users и в таблице content_type_customer странные данные.
> Вот, например, кусок содержимого content_type_customer:
> http://mini7.che.baikalweb.com/import-d6-customers.php?op=customers
>
> Выполняется запрос 'SELECT c.* FROM content_type_customer c LIMIT 1000'
>
Там mix. Дайте мне доступ, я забью руками несколько samples, чтобы это Вас
не смущало.
В БД персональных данных за 10+ лет.
Как у Вас будет готов модуль я готов его оттестировать на реальных данных.

> Используем дамп
> https://www.dropbox.com/s/7cdgkmkxkz2x0gh/mini7-pg94.Fc?dl=0
>
> Ещё скажите какую версию PostgreSQL используем? Может какие-то специфичные
> настройки, ключи или ещё что-то? У нас специалиста по PostgreSQL нет, может
> мы как-то неправильно залили При импорте дампа были какие-то ошибки - не
> знаем, критично или нет.
>
9.4 (как и названии файла).
Ошибки - присоедините import.log сюда же, посмотрим.

**Comment by chernetsky** [comment]
> Как я понимаю, Вы пишете модуль для миграции данных из D6(старая структура) в 7(новая > структура). Т.е. будет модуль, который будет содержать mapping&rules.

Мы не пишем модуль. Пишем простой скрипт, который будет брать данные из старой базы и программно создавать сущности. mapping&rules использоваться не будет.

Есть вопросы:
1. К пользователю может быть привязан только один Покупатель? Или может быть несколько? В наших тестовых данных бывает несколько.
2. Туристы привязаны к Покупателю? Каким запросом можно получить Туристов Покупателя, не используя номер заказа?

**Comment by chernetsky** [comment]
> Покупатель делает заказ и оплачивает Тур.

Это надо тоже разобрать подробнее. Насколько я понял, в базе есть отдельные сущности Заказ и Тур. В старой структуре друпале эти сущности никак не представлены? Друпальский материал ordertable (Заявка в стол заказов) - это же совсем другое?

Что такое Заказ и как пользователь его создаёт?

Ещё предлагаю вам решить, что было не удобно в старой структуре и определиться с тем, как организовать в новой системе Заказы и Туры.

**Comment by alexfourth** [comment]
6 апреля 2015 г., 8:33 пользователь Sergey Chernetsky <notifications@github
.com> написал:

> Как я понимаю, Вы пишете модуль для миграции данных из D6(старая
> структура) в 7(новая > структура). Т.е. будет модуль, который будет
> содержать mapping&rules.
>
> Мы не пишем модуль. Пишем простой скрипт, который будет брать данные из
> старой базы и программно создавать сущности. mapping&rules использоваться
> не будет.
>
Тогда, видимо, у нас недопонимание тут.
В начале 1-го этапа проекта мы переговорили с Вашим руководителем (Антон,
CCed) и решили (по Вашей просьбе)
что сначала делаем основу сайта на D7, включая заказ, а потом пишем
модуль/скрипт для синхронизации
старой и новой БД.

>
>
Есть вопросы:
> 1. К пользователю может быть привязан только один Покупатель? Или может
> быть несколько? В наших тестовых данных бывает несколько.
>
Только у admin есть несколько записей, у остальных по одной.
=> select count(1), uid from node where  type='customer' group by uid
having count(1)>1;
 count | uid
-------+-----
     6 |   0
(1 row)

=>

> 2. Туристы привязаны к Покупателю? Каким запросом можно получить Туристов
> Покупателя, не используя номер заказа?
>
Список пользователя/туристов по UID.

 SELECT nid FROM node WHERE (type='tourist' OR type='customer') AND uid=

**Comment by alexfourth** [comment]
6 апреля 2015 г., 10:34 пользователь Sergey Chernetsky <
notifications@github.com> написал:

> Покупатель делает заказ и оплачивает Тур.
>
> Это надо тоже разобрать подробнее. Насколько я понял, в базе есть
> отдельные сущности Заказ и Турмне.
>
 Мне пока эти описания не доступны (в D7). Есть возможность увидеть?

> В старой структуре друпале эти сущности никак не представлены?
>
Несколько таблиц:
tourindextourists
tourindexcard
tourindex_xml
tourindexorders

Я бы очень рекомендовал посмотреть
sites/all/modules/custom/ctourindex/order.inc,
там все есть (логика&query). Если этого не достаточно, - дайте знать.

> Друпальский материал ordertable (Заявка в стол заказов) - это же совсем
> другое?
>
Вы правы, это другое.

> Что такое Заказ и как пользователь его создаёт?
>
 Заказ(он же заявка) лучше увидеть из под Вашего тестового аккаунта
(test_my) http://mini7.ru/tourinfo/26300314587@511.

> Ещё предлагаю вам решить, что было не удобно в старой структуре и
> определиться с тем, как организовать в новой системе Заказы и Туры.
>
Мы сейчас говорим о модуле/скрипте синхронизации или по системе(D7)  в
целом?

**Comment by alexfourth** [comment]
Я не уверен что стоит это тикет закрывать. Без этого скрипта систему не поднять на новом месте.
