### ISSUE TITLE
Страница с расширеной формой поиска

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#16]
Страница с расширеной формой поиска сейчас отличается от макета.
Причины этого - часть полей, присутствующих в sletat, отсутствует в макете. Другая часть полей, напротив, не работает в sletat.
Посмотрите, устроит ли такой вариант, или нужно внести какие-то изменения.
Посмотреть можно здесь: http://mini7.nava.baikalweb.com/toursearch/advanced

**Comment by alexfourth** [comment]
В этой системе я не зарегистрирован.
Пож. зарегистрируйте меня, emial текущий.

29 апреля 2015 г., 14:51 пользователь Anton L. Safin <
notifications@github.com> написал:

> Страница с расширеной формой поиска сейчас отличается от макета.
> Причины этого - часть полей, присутствующих в sletat, отсутствует в
> макете. Другая часть полей, напротив, не работает в sletat.
> Посмотрите, устроит ли такой вариант, или нужно внести какие-то изменения.
> Посмотреть можно здесь: http://tm.baikalweb.com/issue/GRD-131
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bayclosed/mini7/issues/16>.
>



-- 
Удачи.
Alexander

**Comment by als-studio** [comment]
> В этой системе я не зарегистрирован.
Первая ссылка была неверная. Исправили: http://mini7.nava.baikalweb.com/toursearch/advanced

**Comment by alexfourth** [comment]
Комментарии по странице (полный анализ еще на закончен).

http://mini7.nava.baikalweb.com/toursearch/advanced

Загрузка форма при переходе на нее занимает некоторое время,
небольшое, но видимое (грузятся списки городов вылета и стран).

Нет смысла каждый раз вытаскивать эти списки при каждой загрузке формы,
так как эти поля по сути статичны.


Я бы хотел установить значение полей при первоначальной загрузке,
уточните в каком месте кода это возможно сделать.

Город вылета: Москва (уже есть)
Куда: Турция (на лето)
Дата вылета: тек. дата + 3 
Дата возвращения: Дата вылета + 7 
Продолжительность:	от 7	до 10

	


Не по макету:
над датой возращения не нужно делать запись - "Возвращение"
+-3 дня исчезло
Регион есть по макету нет

А что именно не так, укажите пож.````Другая часть полей, напротив, не работает в sletat.````

**Comment by als-studio** [comment]
Поставлены задачи (#M7-94, #M7-95)

**Comment by alexfourth** [comment]
вопрос с расширенной формой замораживаем, как минимум до полной релизации цепочки: профиль, поиска, тур, заказ.
