### ISSUE TITLE
Как именно будет выглядеть страница "Акции"?

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#2]
Нужно окончательно определится с макетом страницы "Акции".

**Comment by alexfourth** [comment]
Идем по пути  лесенки (горизонтальные), т.е. одна акция одна строчка/tr, легче формировать/воспринимать/подавать.

Сам блок состоит из:
1) Фото
2) Краткое описание
3) Основное описание
4) Кнопка(и) действия(й) (бронирование/связаться)

Если текстовка значительная, то ограничивать блок по высоте, раскрывать при нажатии.

**Comment by als-studio** [comment]
Во вложении - прототип страницы "Акции".
Минус: в такой концепции не очень понятно, как будет выглядеть развернутый блок. Поэтому есть предложение в случае, если описание акции большое, просто создавать отдельную страницу под нее со ссылкой с общей страницы акций.
![action](https://cloud.githubusercontent.com/assets/1411640/6822764/33a907b8-d31d-11e4-84ae-4c42d5733dd6.png)

**Comment by alexfourth** [comment]
Такой задачи и нет, детальная информация будет доступна на отдельной странице или в документе PDF.
````
Минус: в такой концепции не очень понятно, как будет выглядеть развернутый блок. 
````
Кнопка Заказать должна быть меньшего  размера, не больше чем регистрация.
При заказе происходит переход по ссылке (два варианта, взавимости от акции):
1) На форму/результаты поиска 
2) На Стол Заказов  с частично заполненными полями

**Comment by als-studio** [comment]
Пытались сделать кнопки в соответствии со стилем на других страницах.

См. такой вариант:

![action-1](https://cloud.githubusercontent.com/assets/1411640/6899426/e7c556a2-d732-11e4-884f-763a35ae5369.png)

**Comment by alexfourth** [comment]
Визуально, кнопка кажется немного больше, чем кнопка регистрация (скорее из-за capital letters).
Давайте двигаться дальше, как я понимаю, шаблон добавления акции, включая размер/положение кнопки можно будет изменить.

**Comment by als-studio** [comment]
Закрываю
