### ISSUE TITLE
Как должен работать "профиль пользователя"

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#20]
Сейчас в макетах есть две страницы:
05 order 10_06.jpg и 07 user profile 10_06.jpg

На этих страницах есть очень похожий блок - указание данных туриста.
Не понятно, как форма заказа должна взаимодействовать с профилем пользователя.

Посмотрел, как сделано на текущем сайте:
- Есть возможность добавить туристов в профиле пользователя.
- Если туристы в профиль добавлены, в момент оформления заявки можно либо ввести данные нового туриста, либо выбрать существующего из профиля.

Однако в новом макете нет поля для выбора туриста из существующего профиля.
Так же не очень понятно, должен ли турист, которого посетитель сайта добавил при оформлении заказа, добавляться в профиль?

**Comment by alexfourth** [comment]
1 мая 2015 г., 8:54 пользователь Anton L. Safin <notifications@github.com>
написал:

> Сейчас в макетах есть две страницы:
> 05 order 10_06.jpg и 07 user profile 10_06.jpg
>
> На этих страницах есть очень похожий блок - указание данных туриста.
>
Действительно, визуально похоже.

Не понятно, как форма заказа должна взаимодействовать с профилем
> пользователя.
>
При заказе пользователь вносит новых туристов или выбирает из списка уже
имеющихся.
Оптимальней всего прямо в ФИО (Добавить данные туриста) написать выбрать из
списка,
при клике появляется сам список.
Можно воспользоваться выбором из списка, а можно внести информацию с нуля.

Если с этим сложности, то правее от "Добавить данные туриста"  добавить
"выбрать из списка", как в текущей системе.
Также возможно  что при нажатии "ДОБАВИТЬ ТУРИСТА", покупателю предлагается
выбрать из списка или
перейти к пустой форме заполнения если турист новый.


При выборе данные туриста доступны для дальнейшего редактирования.

ВНИМАНИЕ!
Если данные профиля не заполнены, то не возможно продолжение заполнения
заявки.
Пользователю д.б. предложено внести изменения в профиль и после этого
продолжить заполнять заявку.
Если есть такая возможность, то надо предлагать заполнять эти поля прямо в
процессе диалога
заполнения полей заявки (т.е. без перехода в профиль).
Кол-во форм туристов для заполнения при переходе на форму Заявки соответствует
кол-ву туристов в туре/путевки.
Несмотря на это, покупатель может добавить/удалить туристов, т.е.  их м.б.
больше или меньше чем заявлено/ожидается в туре.
Все поля покупателя должны быть заполнены (минимум один телефон),
даты документов не должны быть expired. Даты рождения не должны из будущего.
Тоже касается туристов, пустые или неполные формы не пропускаем.
Фамилия/Имя латиницей должна содержать латинские буквы, ФИО русские.
Маска/проверка ввода телефон и email.

Посмотрел, как сделано на текущем сайте:
>
>    - Есть возможность добавить туристов в профиле пользователя.
>
> Так и должно быть.

>
>    - Если туристы в профиль добавлены, в момент оформления заявки можно
>    либо ввести данные нового туриста, либо выбрать существующего из профиля.
>
> Надо сохранить.

>
>
> Однако в новом макете нет поля для выбора туриста из существующего профиля.
>


> Так же не очень понятно, должен ли турист, которого посетитель сайта
> добавил при оформлении заказа, добавляться в профиль?
>
Должен. В профиле предъявляются все туристы привязанных к пользователю.

**Comment by als-studio** [comment]
Продолжение темы здесь: #25

**Comment by alexfourth** [comment]
#25 - это заказ тура, тут мы речь шла о Профиле.
Да, конечно, большинство, если не все проверки один в один,
но реализация заказа тура не снимает задач по профилю.
