### ISSUE TITLE
Drupal Releases Security Updates applied?

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#21]
Уточните пож. если указанные ниже updates были/будут включены в поставку.
--------- Forwarded message ----------
From: "US-CERT" <US-CERT@ncas.us-cert.gov>
Date: Mar 20, 2015 12:47 AM
Subject: Drupal Releases Security Updates

 NCCIC / US-CERT

National Cyber Awareness System:

Drupal Releases Security Updates
03/19/2015 05:48 PM EDT

Original release date: March 19, 2015
Drupal has released updates to address multiple vulnerabilities, one of which could allow a remote attacker to gain access to a system account.

Available updates include:

*         Drupal core 6.35 for 6.x users

*         Drupal core 7.35 for 7.x users

US-CERT encourages users and administrators to review Drupal's Security Advisory and apply the necessary updates.

This product is provided subject to this Notification and this Privacy & Use policy.

OTHER RESOURCES:
Contact Us | Security Publications | Alerts and Tips | Related Resources
STAY CONNECTED:
Sign up for email updates
SUBSCRIBER SERVICES:
Manage Preferences  |  Unsubscribe  |  Help

This email was sent to bayclosed@gmail.com using GovDelivery, on behalf of: United States Computer Emergency Readiness Team (US-CERT) · 245 Murray Lane SW Bldg 410 · Washington, DC 20598 · (888) 282-0870	Powered by GovDelivery

**Comment by mrsad** [comment]
конечно. текущая версия Drupal Core 7.36

01.05.2015 22:35, alexfourth пишет:
