### ISSUE TITLE
Регистрация (в текущем виде отпугнет)

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#22]
Несмотря на то что реализация регистрации не входит в текущие краткосрочные планы, 
я хотел бы сделать комментарий по этому вопросу.

Я случайно обнаружил что при регистрации запрашивается вся информация по профилю.
http://mini7.nava.baikalweb.com/ajax_register/register/nojs

В таком виде не планировалось, т.е. при регистрации запрашивается минимальная информация, а вот при заказе система попросит заполнить все. Иначе пользователи увидев что нужно вводить персональные данные, да еще в таком кол-ве, не дойдут до заказа.

**Comment by als-studio** [comment]
Добавил в уточнение в задачу (#M7-38)
