### ISSUE TITLE
Нет возможности получить информацию об отелях с sletat

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#24]
Пока нет возможности получить информацию об отеле. Вызов функции выдаёт такую ошибку:

SoapFault: Нет подходящей лицензии для использования шлюза Отелей. Свяжитесь со службой поддержки info@sletat.ru.

**Comment by alexfourth** [comment]
Модуль активирован, прошу проверить.

**Comment by als-studio** [comment]
Да, доступ появился, спасибо.
