### ISSUE TITLE
Заказ тура

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#25]
В процессе реализации заказа тура поняли, что не до конца согласовали логику заказа.

Как это представляем себе мы.

**В случае зарегистрированного пользователя** (у которого заполнен, хотя бы частично, профиль в личном кабинете):

1. Пользователь входит на сайт со своей учетной записью.

2. Пользователь ищет тур, нажимает кнопку "заказать" на странице результатов поиска или на странице тура. Попадает на страницу "Заявка"

3. По умолчанию в форме два блока - "добавить данные туриста" и все, что находится в макете ниже кнопки "Добавить туриста". 
3.1. При вводе текста в поле Ф.И.О. в форме "добавить данные туриста" должен появляться выпадающий список (autocomplete), содержащий частично совпадающие Ф.И.О. туристов из профиля пользователя. При выборе существующего туриста его данные подставляются в форму. При этом у пользователя должна быть возможность отредактировать данные в форме (однако в профиле они при этом не обновляются!). При клике на кнопку "Сохранить" формируется свернутый блок выше формы "Добавить данные туриста" с Ф.И.О. туриста в заголовке: https://yadi.sk/i/nwE2cozlgfKxV
При нажатии на "крестик" в левом верхнем углу поля формы обнуляются.
3.2. Если введена фамилия, которой нет в заполненном профиле пользователя, все данные вводятся вручную (все данные формы обязательны к заполнению). После нажатия кнопки "Сохранить" так же формируется свернутый блок с Ф.И.О. туриста (как в п.3.1), однако при этом вновь введенные данные сохраняются в профиль пользователя.

4. В сворачивающемся блоке с Ф.И.О. туриста (https://yadi.sk/i/nwE2cozlgfKxV) данные НЕ РЕДАКТИРУЮТСЯ (можно предусмотреть это на дальнейших этапах развития проекта). Для редактирования данных необходимо перейти в профиль пользователя и отредактировать их там. 
При клике по кнопке "Удалить туриста" блок с Ф.И.О. туриста удаляется из заявки, но не из профиля.

5. После заполнения ВСЕХ полей формы и нажатия кнопки "Оформить" данные формы отправляются в sletat.ru. Обратите внимание на то, что sletat.ru (метод SaveTourOrder) принимает только часть данных: данные выбранного тура, имя туриста, контактный email, телефон и комментарий.

6. Результаты формы так же отправляются на email менеджеру сайта. (Нужно ли это? Не помню, обговаривали ли мы этот момент.)

7. Заказ сохраняется в личном кабинете пользователя.

**В случае анонимного пользователя**:

Все аналогично зарегистрированному пользователю, за исключением некоторых моментов:
- Нет autocomplete (выбора из списка) при заполнении поля Ф.И.О. при добавлении туриста.
- Данные заказа не сохраняются в личном кабинете пользователя (его просто не существует).

При дальнейшем развитии проекта можно предусмотреть автоматическую регистрацию пользователя после заполнения и отправки заявки, с сохранением заявки и заполненных полей (туристов) в профиле пользователя.

**Валидация полей**:
Все поля покупателя должны быть заполнены (минимум один телефон),
даты документов не должны быть expired. Даты рождения не должны из будущего.
Тоже касается туристов, пустые или неполные формы не пропускаем.
Фамилия/Имя латиницей должна содержать латинские буквы, ФИО русские.
Маска/проверка ввода телефон и email.

Все верно?

**Comment by als-studio** [comment]
Итого, то, что мы сейчас не делаем, но можно предусмотреть в планах развития проекта (для удобства пользователя):
1. Сохранение измененных данных о туристе на странице "Заявка" в форме "Добавить туриста" в профиль пользователя - возможно, с возможностью выбора (к примеру, всплывающее окно с вопросом "Изменить эти данные в вашем профиле"?)
2. Возможность редактирования данных в раскрывающемся блоке с Ф.И.О. туриста, сохранение изменений в профиле пользователя
3. Автоматическая регистрация анонимных пользователей при оформлении заявки.

**Comment by alexfourth** [comment]
16 мая 2015 г., 5:40 пользователь Anton L. Safin <notifications@github.com>
написал:

> В процессе реализации заказа тура поняли, что не до конца согласовали
> логику заказа.
>
> Как это представляем себе мы.
>
> *В случае зарегистрированного пользователя* (у которого заполнен, хотя бы
> частично, профиль в личном кабинете):
>
>    1.
>
>    Пользователь входит на сайт со своей учетной записью.
>
>
>    1.
>
>    Пользователь ищет тур, нажимает кнопку "заказать" на странице
>    результатов поиска или на странице тура. Попадает на страницу "Заявка"
>
> У пользователя должна быть возможность авторизоваться с этого шага. Т.е.
зашел на сайт начал искать, нашел что хотел и лишь после этого решил ввести
свой логин/пароль, а возможно и зарегистрироваться (если до этого не
сделал),
при процесс регистрации мы не должны потерять его результаты поиска/тур. В
текущей версии сайта оба этих пункта реализованы.

>
>    1.
>
>    По умолчанию в форме два блока - "добавить данные туриста" и все, что
>    находится в макете ниже кнопки "Добавить туриста".
>    3.1. При вводе текста в поле Ф.И.О. в форме "добавить данные туриста"
>    должен появляться выпадающий список (autocomplete),
>
> Напишите в поле фразу типа "Начинайте вводить Фамилию"  и/или что-то
подобное чтобы было четко понятно то делать.

>
>    1.
>
>    содержащий частично совпадающие Ф.И.О. туристов из профиля
>    пользователя. При выборе существующего туриста его данные подставляются в
>    форму. При этом у пользователя должна быть возможность отредактировать
>    данные в форме (однако в профиле они при этом не обновляются!).
>
> Согласовано.

>
>    1.
>
>    При клике на кнопку "Сохранить" формируется свернутый блок выше формы
>    "Добавить данные туриста" с Ф.И.О. туриста в заголовке:
>    https://yadi.sk/i/nwE2cozlgfKxV
>    При нажатии на "крестик" в левом верхнем углу поля формы обнуляются.
>
> Крестика не вижу, как я понимаю он появится. Хорошо.

>
>    1.
>
>    3.2. Если введена фамилия, которой нет в заполненном профиле
>    пользователя, все данные вводятся вручную (все данные формы обязательны к
>    заполнению). После нажатия кнопки "Сохранить" так же формируется свернутый
>    блок с Ф.И.О. туриста (как в п.3.1), однако при этом вновь введенные данные
>    сохраняются в профиль пользователя.
>
> Принимается, данные по новым туристам сохраняются в профиль пользователя,
данные отредактированных туристов в профиле остаются без изменений.

>
>    1.
>
>    В сворачивающемся блоке с Ф.И.О. туриста (
>    https://yadi.sk/i/nwE2cozlgfKxV) данные НЕ РЕДАКТИРУЮТСЯ (можно
>    предусмотреть это на дальнейших этапах развития проекта). Для
>    редактирования данных необходимо перейти в профиль пользователя и
>    отредактировать их там.
>
> ок

>
>    1.
>
>    При клике по кнопке "Удалить туриста" блок с Ф.И.О. туриста удаляется
>    из заявки, но не из профиля.
>
> ок

>
>    1.
>
>    После заполнения ВСЕХ полей формы и нажатия кнопки "Оформить" данные
>    формы отправляются в sletat.ru. Обратите внимание на то, что sletat.ru
>    (метод SaveTourOrder) принимает только часть данных: данные выбранного
>    тура, имя туриста, контактный email, телефон и комментарий.
>
> Тут не так.
ВНИМАНИЕ!!! У нас нет необходимости сохранять заявку в слетать. Все делаем
локально.
Т.е. заявка во ВСЕМИ полями сохраняется у нас в БД и только у нас.

>
>    1.
>
>    Результаты формы так же отправляются на email менеджеру сайта.
>
> Этот пункт оставляем. В настройках друпал должна быть возможность указать
на какой адрес высылать сообщение.
ДОПОЛНЕНИЕ!!!
Также надо высылать пользователю информацию о заказе, который он(а)
совершил(а) (формат сообщения редактируем в друпал, так реализовано в
текущей системе).

Пример эл. сообщения из текущей системы:
> Здравствуйте.
>
> Вы оформили заказ в интернет-магазине путевок mini7 со следующими данными:
>
> Греция на 26.07.2015
> Курорт: Крит о.
> Отправление из: Москва
> Отель: CHC Sea Side Resort & Spa 5*
> Продолжительность тура: 7
> Дата возвращения: 02.08.2015
> Тип комнаты: Superior
> Питание: AI
> Страховка: включена
> Трансфер: включен
> Кол-во туристов: 3
> Кол-во взрослых: 2
> Цена: 2033&euro;
> Ваша цена (-5%): 1932&euro;
> -----------
> Заказ принят к рассмотрению.
> Наши менеджеры свяжутся с Вами в ближайшее время.
>
> Номер вашего заказа: 27121104996
>
> Интернет-магазин mini7
> http://mini7.ru

На email менеджера (это booking@mini7.ru) информация отправляется в
расширенном виде.
И в первом и во втором случаях письма отправляются от info@mini7.ru

>
>    1.
>
>    Заказ сохраняется в личном кабинете пользователя.
>
> ок. Только как он может увидеть его далее?

>
>
> *В случае анонимного пользователя*:
>
> Все аналогично зарегистрированному пользователю, за исключением некоторых
> моментов:
>
>    - Нет autocomplete (выбора из списка) при заполнении поля Ф.И.О. при
>    добавлении туриста.
>
> ок

>
>    - Данные заказа не сохраняются в личном кабинете пользователя (его
>    просто не существует).
>
> Заказ не пройдет без ввода паспортных данных покупателя (они только в
кабинете).
Если Вы сможете собрать данную информацию и завершить заказ - без проблем
(в текущей версии сайта этого нет).

>
>
> При дальнейшем развитии проекта можно предусмотреть автоматическую
> регистрацию пользователя после заполнения и отправки заявки, с сохранением
> заявки и заполненных полей (туристов) в профиле пользователя.
>
Подумаем позднее про автоматическую регистрацию.

> *Валидация полей*:
> Все поля покупателя должны быть заполнены (минимум один телефон),
>
мы говорим о полях покупателя, т.е. по факту о почти всех полях профиля
(форма user profile)?
Если да, то ок, если нет, то уточните о чем идет речь.

>
>
даты документов не должны быть expired.
>
ок

> Даты рождения не должны из будущего.
>
ок

> Тоже касается туристов, пустые или неполные формы не пропускаем.
>
ок

> Фамилия/Имя латиницей должна содержать латинские буквы, ФИО русские.
>
Да, но добавьте к этому тире, чтобы закрыть сложные фамилии.

> Маска/проверка ввода телефон и email.
>
ок

> Все верно?
>
Комментарии выше.
