### ISSUE TITLE
Captcha в форме регистрации

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#26]
Есть небольшая проблема с Captcha в форме регистрации пользователя.
Так как всю валидацию мы сделали без перезагрузки страницы (AJAX), после неверного заполнения формы изображение в "капче" не обновляется.
Мы можем потратить на исправление этого достаточно много времени. Поэтому предлагаем альтернативный вариант - поставить "невидимую капчу" (к примеру, https://www.drupal.org/project/honeypot). Как правило, эта защита не намного уступает стандартной "капче с картинкой", однако не напрягает пользователей и позволит решить вопрос с обновлением формы.

**Comment by alexfourth** [comment]
У меня нет опыта использования данного модуля.
По описанию и отзывам достойная замена Captcha.

16 мая 2015 г., 6:28 пользователь Anton L. Safin <notifications@github.com>
написал:

> Есть небольшая проблема с Captcha в форме регистрации пользователя.
> Так как всю валидацию мы сделали без перезагрузки страницы (AJAX), после
> неверного заполнения формы изображение в "капче" не обновляется.
> Мы можем потратить на исправление этого достаточно много времени. Поэтому
> предлагаем альтернативный вариант - поставить "невидимую капчу" (к примеру,
> https://www.drupal.org/project/honeypot). Как правило, эта защита не
> намного уступает стандартной "капче с картинкой", однако не напрягает
> пользователей и позволит решить вопрос с обновлением формы.
>
Используйте это решения для всех открытых форм сайта (как я понимаю это
только вопрос настройки модуля/формы и занимает несколько минут).

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bayclosed/mini7/issues/26>.
>



-- 
Удачи.
Alexander

**Comment by als-studio** [comment]
Ok.
Закрываю.
