### ISSUE TITLE
При регистрации теряются параметры сессии

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#28]
После регистрации, при закрытии формы, получаем вот такую ошибку.

Notice: Undefined variable: _SESSION в функции _initFormParams() (строка 858 в файле /home/nava/www/nava.baikalweb.com/mini7/sites/all/modules/custom/toursearch/toursearch.module).

**Comment by alexfourth** [comment]
такая же ошибка возникает при выходе из личного кабинета (при нажатии кнопки Выход)
Notice: Undefined variable: _SESSION в функции _initFormParams() (строка 858 в файле /home/nava/www/nava.baikalweb.com/mini7/sites/all/modules/custom/toursearch/toursearch.module).

**Comment by mrsad** [comment]
Это давным давно исправлено.
