### ISSUE TITLE
Стол заказов, ошибка при отправке заказа

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#33]
При нажатии кнопки отправить (с полями как на форме ниже)
![2015-05-28 08-49-55 - - google chrome](https://cloud.githubusercontent.com/assets/3527668/7854117/95a28126-0516-11e5-9c69-80eda908ce0c.png)

 возникает следующая ошибка.
````
Fatal error: Class 'libphonenumber\DefaultMetadataLoader' not found in /home/nava/www/nava.baikalweb.com/mini7/sites/all/libraries/libphonenumber-for-php/src/libphonenumber/PhoneNumberUtil.php on line 341
````

**Comment by mrsad** [comment]
Не смог воспроизвести. Возможно была рассинхронизация кода у разработчиков и верстальщика.

**Comment by alexfourth** [comment]
Возможно, больше не проявляется.
