### ISSUE TITLE
Вид меню второго уровня на страницах "Как мы работаем"

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#4]
Изменяем ли вид меню второго уровня на страницах "Как мы работаем" - и если да, то как?
http://mini7.nava.baikalweb.com/7steps

**Comment by alexfourth** [comment]
Как я понимаю речь идет о кнопках/блоках7 шагов, Наши документы и т.д.
По моему мнению эти кнопки/блоки немного подвешены, 
пока примелимой альтернативы нет.

**Comment by als-studio** [comment]
Вариант 3 (как у apple):

![submenu-3](https://cloud.githubusercontent.com/assets/1411640/6822943/89c2762e-d31e-11e4-98b2-804ec4d2790d.png)

Вариант 4 (со вкладками). Этот вариант лучше с точки зрения юзабилити, но он будет странно смотреться в случае, когда зона контента разбита на блоки (к примеру, как в "7 шагах") - будет ощущение, что вкладки имеют отношение только к первому блоку.

![submenu-4](https://cloud.githubusercontent.com/assets/1411640/6822966/aef7bc60-d31e-11e4-9d35-3cd44db94b0d.png)

**Comment by alexfourth** [comment]
При наличии второго уровня, предлагаю не выводить "Как мы работаем",
а сразу выводить второй уровень меню, без текстовки(т.е. вариант 3 с изменениями).
Иначе, эта часть кажется перегруженной если у нас два уровня.

**Comment by als-studio** [comment]
То есть такой вариант, верно?

![submenu-5](https://cloud.githubusercontent.com/assets/1411640/6899153/31b2bb76-d731-11e4-990b-ddf0ccb12b65.png)

**Comment by alexfourth** [comment]
Еще раз просмотрели группой все предложенные варианты.

Идем по Варианту 4 (со вкладками), там есть конечно вопросы к 7 шагам, но
последний вариант получается на порядок хуже.

2015-03-30 17:06 GMT+02:00 Anton L. Safin <notifications@github.com>:

> То есть такой вариант, верно?
>
> [image: submenu-5]
> <https://cloud.githubusercontent.com/assets/1411640/6899153/31b2bb76-d731-11e4-990b-ddf0ccb12b65.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bayclosed/mini7/issues/4#issuecomment-87716156>.
>



-- 
Удачи.
Alexander

**Comment by als-studio** [comment]
Добрый день!
Посмотрите, пожалуйста, страницу с вторым уровнем меню: http://mini7.nava.baikalweb.com/7steps
Есть ли замечания?

**Comment by alexfourth** [comment]
Замечаний по меню второго уровня нет.
