### ISSUE TITLE
Не все картинкам/изображения доступны в git (невозможно продолжить тестирование)

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#41]
Часть картинок не прогружаются/не доступны http://sonda.mini7.ru:6251/.

Мы забрали все с git, но там стоит soft link.
https://github.com/bayclosed/mini7/tree/master/sites

sites - default -> ../../../../shared-data/mini7/default

Ка получить доступ к этим картинкам/изображениям?

**Comment by mrsad** [comment]
в архиве, доступном по ссылке http://dev.baikalweb.com/mini7.tar.gz все 
файлы на месте. удалите ссылку в git и замените на файлы из архива

05.10.2015 18:52, alexfourth пишет:

**Comment by alexfourth** [comment]
Картинки обнаружили в день обращения, частично с этим вопрос уже решили/закрыли.

В процесс разбора/понимания обнаружили несколько директорий где
хранятся фотки, как я понимаю отелей.

sites/default/files
					externals - фотки отелей (~80M)
					styles/hotel_slider - фотки отелей для слайдера (25M)
					styles/tour_teaser -  фотки отелей (69M)

Как Вы сформировали/заполнили их?
Зачем это сделано? (как я помню предполагалось читать напрямую со слетать.ру)

**Comment by mrsad** [comment]
разобрался. для соответствия дизайну фотографии обрабатываются стилями (image_style). т.е. скачиваются и конвертируются при помощи модулей imagecache_external, imagecache_actions и image.

**Comment by alexfourth** [comment]
Петр, спасибо. Но об этом(конвертация) мы знали еще как минимум неделю назад.
Вопрос возник из-за того, что если не перести картинки, то система не загружает их заново.

Два  вопроса по сути остались без ответа.
|Как Вы сформировали/заполнили их?
|Зачем это сделано? (как я помню предполагалось читать напрямую со слетать.ру)

**Comment by mrsad** [comment]
|Как Вы сформировали/заполнили их?

используя тему из imagecache_external.
примерно так:
```php
$tmp = explode('.jpg', $tourData->HotelTitleImageUrl);
$imagePath = $tmp[0] . '_170_244.jpg';
$hotelImage = array(
                    '#theme' => 'imagecache_external',
                    '#path' => $imagePath,
                    '#style_name' => 'tour_teaser',
                    '#alt' => $tourData->TourName,
);
echo render($hotelImage);
```

см. функцию _renderRows из toursearch.module

|Зачем это сделано?

ответил уже. для приведения в соответствующий дизайну вид. насколько я помню, там соотношение сторон неподходящее и требовалась обрезка.

**Comment by alexfourth** [comment]
|используя тему из imagecache_external.
Проблема была с Imagecache External, обновил кэш и проблема ушла.
