### ISSUE TITLE
Вид формы на странице "Стол заказов"

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#5]
Изменяем ли вид формы на странице "Стол заказов" - и если да, то как?

**Comment by alexfourth** [comment]
Попробовать можно, но как это будет выглядеть вопрос, надо смотреть.
Логически можно объединить (в одну строку 50%+50%):
	Email + Телефон
	Ориентировочная дата выезда + Продолжительность, вторая поднимается вверх к первой
	Количество человек + В какую сумму желаете уложиться

Если поле необязательное убрать/заменить желтый цвет рамки, относится только к "Как вы о нас узнали?" и "Дополнительная информация".

Если поле обязательно для заполнения, но нет данных, то это поле(рамка) должно подсвечиваться красным цветом после нажатия кнопки отправить.

**Comment by als-studio** [comment]
Попытались разбить поля в форме на несколько групп - это позволило структурировать форму, за счет этого упросить ее визуально:

![orderform](https://cloud.githubusercontent.com/assets/1411640/6823370/4a5045c6-d322-11e4-8735-44d3a9083112.png)

Вариант полей без желтой обводки:

![orderform1](https://cloud.githubusercontent.com/assets/1411640/6823419/d318f33a-d322-11e4-939f-bf102c9a9eef.png)

Чтобы желтая обводка не бросалась в глаза, можно сделать форму вывороткой (т.е. на темном фоне, как в макете user profile). Пример (весьма грубый набросок, чтобы не тратить время на отрисовку):

![orderform_invert](https://cloud.githubusercontent.com/assets/1411640/6823495/a6028d74-d323-11e4-8132-49c865001256.png)

**Comment by alexfourth** [comment]
Двигаемся дальше с вариантом с разбивкой, где все поля с желтой обводкой.
````
Попытались разбить поля в форме на несколько групп
````
Дополнение.
Сама обводка является прежде всего элементом дизайна(Вы на это также обращали внимание).
Все поля этой формы, кроме 2-х дополнительных являются обязательными,
поэтому их (кроме Как Вы о нас узнали + Доп. информация) нужно подсвечивать красным если они остались незаполненными, дублируя фразой красным "Это поле должно быть заполнено".
Желательно выполнять эти действия (изменение подсветки + фраза) сразу в процессе заполнения формы.

**Comment by als-studio** [comment]
Уточните, какой вариант формы выбираем - на светлом фоне, или на темном?

**Comment by alexfourth** [comment]
на светлом.

30 марта 2015 г., 17:01 пользователь Anton L. Safin <
notifications@github.com> написал:

> Уточните, какой вариант формы выбираем - на светлом фоне, или на темном?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bayclosed/mini7/issues/5#issuecomment-87714751>.
>



-- 
Удачи.
Alexander

**Comment by als-studio** [comment]
Сделали такой вариант: http://mini7.nava.baikalweb.com/webform/29

**Comment by alexfourth** [comment]
понял, спасибо, несколько комментариев/замечаний ниже (скриншот поясняющий
в приложении).


   1. Поле телефон немного смещено влево (Телефон/текст слишком близко к
   полю email)
   2. Продолжительность/текст не по центру поля
   3. "Как Вы узнали" без обрамления (как и для других полей, см.
   предыдущий комментарий)
   4. "Доп. информация" без обрамления (как и для других полей, см.
   предыдущий комментарий)


2015-04-06 3:52 GMT+02:00 Anton L. Safin <notifications@github.com>:

> Сделали такой вариант: http://mini7.nava.baikalweb.com/webform/29
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bayclosed/mini7/issues/5#issuecomment-89887526>.
>



-- 
Удачи.
Alexander

**Comment by als-studio** [comment]
Исправлено по вашим замечаниям.
http://mini7.nava.baikalweb.com/webform/29

**Comment by alexfourth** [comment]
По визуализации вопросов нет.

По заполнению:
Как минимум надо проверять правильность ввода email и телефона.
Это единственная возможность обратной связи, если эта информация не будет введена правильно, то заявка уйдет в /dev/null.
Сейчас вводишь любой символ и проходишь дальше.

**Comment by als-studio** [comment]
Передал в работу, номер задачи M7-82
