### ISSUE TITLE
Страницы для печати

### ISSUE THREAD

**Issue by als-studio** [bayclosed/mini7#6]
Делаем ли страницы для печати, какой механизм используем (генерация PDF, отдельный шаблон для страницы или стиль для принтера), как должна выглядеть иконка для отправки на печать?

**Comment by alexfourth** [comment]
Просмотрев несколько примеров, PDF-версия отпадает. 
Все основные документы уже(и будут) представлены в PDF.
Т.е. для них проблем печати нет, остается только вопрос контента, в этом случае лучше решить это через "отдельный шаблон для страницы или стиль для принтера".
Как удобнее/лучше, у меня ответа нет, примите решение сами, исходя из поинимания задачи.

Пример расположения:
http://tonkosti.ru/%D0%90%D0%BD%D0%B4%D0%BE%D1%80%D1%80%D0%B0
Версия для печати

Сама иконка:
Любая подходящая по дизайну и фону(примеры: http://findicons.com/search/printer)

Пока предлагаю ф-ции печати не реализовывать (pending).

**Comment by als-studio** [comment]
Пока закрываю.
