### ISSUE TITLE
Несоотвествие фото оригиналу на главной

### ISSUE THREAD

**Issue by alexfourth** [bayclosed/mini7#8]
Несоотвествие фото оригиналу на главной
http://mini7.nava.baikalweb.com/advancedsearch для
Трансфер
Авиабилеты
Акция 7% к Вашему счастью
Путешествий с друзьями
о компании

Есть техн. причины для этого?

**Comment by als-studio** [comment]
Вопрос еще актуален?

**Comment by alexfourth** [comment]
Да, если мы говорим о песочнице http://mini7.nava.baikalweb.com/advancedsearch, там часть фото на главной не соотвествуют оригиналу.

**Comment by chernetsky** [comment]
С картинками ситуация такая: эти промо-материалы полностью редактируемы, картинки в них загружаются такие, какие захочет админ сайта. Картинки могут быть любого адекватного разрешения и преобразуются движком сайта  в нужный размер в зависимости от позиции материала на странице.

Для создания этих тестовых материалов были использованы случайные тестовые картинки из интернета, подходящие по тематике. Т.е. так, как это будет делать заказчик. Использовать картинки из дизайна не удобно, потому что они маленькие, их надо вырезать + это не моделирует реальную работу с сайтом.

Если необходимо использовать именно те изображения, которые использованы в макете, то их надо где-то добыть в виде самостоятельных отдельных фотографий.

**Comment by alexfourth** [comment]
У меня пока не было возможности проверить, как можно добавлять/изменять.
```
Для создания этих тестовых материалов были использованы случайные тестовые картинки    
из интернета, подходящие по тематике. Т.е. так, как это будет делать заказчик. 
Использовать картинки из дизайна не удобно, потому что они маленькие, их надо вырезать 
+ это не моделирует реальную работу с сайтом.
```

Макеты должны были содержать все исходники, в процессе уточнения.
```
Если необходимо использовать именно те изображения, которые использованы в макете, то их надо где-то добыть в виде самостоятельных отдельных фотографий.
```

**Comment by als-studio** [comment]
В макетах есть исходники (они там в виде smart object). Это что-то наши верстальщики не доглядели.

**Comment by alexfourth** [comment]
Внесите пож. изменения, хотелось бы иметь максимально близкий к оригиналу макета(ов).
```
В макетах есть исходники (они там в виде smart object). 
```

**Comment by als-studio** [comment]
Фото заменили.

**Comment by alexfourth** [comment]
спасибо
